export const QUIZ_ATTEMPT_GRADING_CHANNEL = "quiz_attempt_grading_jobs";
export const QUIZ_ATTEMPT_GRADING_RECONCILE_INTERVAL_MS = 10_000;
export const QUIZ_ATTEMPT_JOB_STALE_AFTER_MS = 2 * 60_000;
export const QUIZ_ATTEMPT_JOB_HEARTBEAT_INTERVAL_MS = 15_000;
